#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bash ~/display.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer       true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

sxhkd&
compton&
bash ~/.config/polybar/launch.sh --forest&
feh --bg-scale --random ~/Pictures/wallpapers&
