#!/bin/sh

percent=$(echo $(acpi) | awk '{print $4}' | sed 's/..$//')
stat=$(echo $(acpi) | awk '{print $3}' | sed 's/.$//')

icon() {
  if [[ $stat == "Discharging" ]]; then
    if [[ "$percent" == "100" ]]; then
      echo 
    elif [[ "$percent" -ge "90" ]]; then
      echo 
    elif [[ "$percent" -ge "80" ]]; then
      echo 
    elif [[ "$percent" -ge "70" ]]; then
      echo 
    elif [[ "$percent" -ge "60" ]]; then
      echo 
    elif [[ "$percent" -ge "50" ]]; then
      echo 
    elif [[ "$percent" -ge "40" ]]; then
      echo 
    elif [[ "$percent" -ge "30" ]]; then
      echo 
    elif [[ "$percent" -ge "20" ]]; then
      echo 
    elif [[ "$percent" -ge "10" ]]; then
      echo 
    else
      echo 
    fi

  else
    if [[ "$percent" == "100" ]]; then
      echo 
    elif [[ "$percent" -ge "90" ]]; then
      echo 
    elif [[ "$percent" -ge "80" ]]; then
      echo 
    elif [[ "$percent" -ge "70" ]]; then
      echo 
    elif [[ "$percent" -ge "60" ]]; then
      echo 
    elif [[ "$percent" -ge "50" ]]; then
      echo 
    elif [[ "$percent" -ge "40" ]]; then
      echo 
    elif [[ "$percent" -ge "30" ]]; then
      echo 
    elif [[ "$percent" -ge "20" ]]; then
      echo 
    elif [[ "$percent" -ge "10" ]]; then
      echo 
    else
      echo 
    fi
  fi
}

if [[ $1 = "-l" ]]; then
  if [[ $stat == "Discharging" ]]; then
    echo "${percent}%"
  else
    echo "Charging: ${percent}%"
  fi
elif [[ $1 = "-i" ]]; then
  icon
fi
