#!/bin/sh

# Lets round the float result
bri=$(echo $(brightnessctl) | awk '{print $9}' | cut -c 2- | sed 's/..$//')

icon() {
  if [[ "$bri" -gt "66" ]]; then
    echo 
  elif [[ "$bri" -gt "33" ]]; then
    echo 
  else
    echo 
  fi
}

if [[ $1 = "-l" ]]; then
  b=$(light -G)
  bri=$(echo "($b+0.5)/1" | bc)
  echo $bri
elif [[ $1 = "-i" ]]; then
  icon
fi
